# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/aabua/Documents/ECE350/flappyECE350/flappyVivado/flappyVivado.runs/synth_1/flappy_Wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/aabua/Documents/ECE350/flappyECE350/flappyVivado/flappyVivado.cache/wt [current_project]
set_property parent.project_path C:/Users/aabua/Documents/ECE350/flappyECE350/flappyVivado/flappyVivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/aabua/Documents/ECE350/flappyECE350/flappyVivado/flappyVivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/processor_memory.mem
read_verilog -library xil_defaultlib {
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/two_bit_comp.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/bit32_comp.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SRA8.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/bypass.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/adder8.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SRA4.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/decode_stage.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/mux_16_32bits.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/processor.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SRA2.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/counter.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/sx16.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/memory_stage.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/mux_4_32bits.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/register.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/mux_16.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SLL.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/mux_32_32bits.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SLL1_div.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/multiplier.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/Wrapper.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/execute_stage_ALU.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/counter3.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/RAM.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SRA16.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/register64.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/alu.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/stall.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/VGATimingGenerator.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SLL2.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/adder32.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/writeback_stage.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SLL4.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/eight_bit_comp.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SLL8.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/Wrapper_tb.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/execute_stage_MultDiv.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/AND.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/VGAController.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/mux_2_32bits.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/mux_8_32bits.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/OR.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SRA1.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/register32.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/sub.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/ROM.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/division.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/multiplication.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/mux_8.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/mux_32.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/control.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/dffe_ref.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/mux_4.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/mux_2.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/regfile.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/flappy_Wrapper.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/counter2.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/decoder_5bits.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/triStateBuff_32.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/register65.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SRA1_mult.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/divider.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SLL1.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SRA.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/SLL16.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/exception_check.v
  C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/multdiv.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/aabua/Documents/ECE350/flappyECE350/RNA_Processor/processor/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top flappy_Wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef flappy_Wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file flappy_Wrapper_utilization_synth.rpt -pb flappy_Wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
